maintainer        "37signals"
maintainer_email  "sysadmins@37signals.com"
description       "Configures dns"
long_description  "Configures#{cookbook.name}"
version           "0.1"
recipe            "dns::client"
