maintainer        "37signals"
maintainer_email  "sysadmins@37signals.com"
description       "Configures nginx"
version           "0.1"
recipe            "nginx::memcache_proxy"
depends           "memcached"