maintainer        "37signals"
maintainer_email  "sysadmins@37signals.com"
description       "Configures chef"
version           "0.7"
depends           "runit"
depends           "logrotate"
depends           "apache2"
depends           "openssl"
depends           "couchdb"
depends           "passenger"
