maintainer        "37signals"
maintainer_email  "sysadmins@37signals.com"
description       "Configures chef"
version           "0.7"
recipe            "chef::client"
recipe            "chef::server"
depends           "runit"
depends           "logrotate"
depends           "apache2"
depends           "openssl"
depends           "couchdb"
