maintainer        "37signals"
maintainer_email  "sysadmins@37signals.com"
description       "Configures djbdns"
version           "0.1"
recipe            "djbdns::autozone"
recipe            "djbdns::axfr"
recipe            "djbdns::cache"
recipe            "djbdns::internal_server"
recipe            "djbdns::server"
depends           "build"
depends           "runit"