maintainer        "37signals"
maintainer_email  "sysadmins@37signals.com"
description       "Configures memcached"
version           "0.1"
recipe            "memcached::basic"
recipe            "memcached::instances"
depends           "runit"