maintainer        "37signals"
maintainer_email  "sysadmins@37signals.com"
description       "Configures nfs"
long_description  "Configures#{cookbook.name}"
version           "0.1"
recipe            "nfs::client"
